version: '3'
services:
    app:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./
        volumes:
            - /app/node_modules
            - ./:/app/
        ports:
            - '5173:5173'
        env_file:
            - ./.env
    edgedb:
        image: edgedb/edgedb
        env_file:
            - ./.env
        volumes:
            - ./edgedb_data:/var/lib/edgedb/data
            - "./dbschema:/dbschema"
        ports:
            - "5656:5656"
